version: '3.8'

services:
  adonis_app:
    container_name: face_recognition
    image: face-recognition
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      - /home/node/app/node_modules
    command: dumb-init node ace serve --watch --encore-args="--host ${HOST}"
    networks:
      - face-network
networks:
  face-network:
    driver: bridge
